kind: Deployment
apiVersion: apps/v1
metadata: 
   name: mydeploy
spec:
   replicas: 2
   selector:
        matchLabels:
             name: deployment
   template:
        metadata:
           name: mypod
           labels: 
             name: deployment
        spec:
          containers: 
            - name: c1
              image: ubuntu
              command: ["/bin/bash", "-c", "while true; do echo 2nd deployment; sleep 5; done"]


