apiVersion: v1
kind: Pod
metadata:
  name: hostpathvol
spec:
  containers:
  - image: centos
    name: cont1
    command: ["/bin/bash", "-c", "sleep 15000"]
    volumeMounts:
    - mountPath: /mnt/hostpath
      name: testvolume
  volumes:
  - name: testvolume
    hostPath:
      path: /tmp/data 
