kind: Deployment
apiVersion: apps/v1
metadata:
   name: mydeployment
spec:
   replicas: 1
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     name: httpdeploy
   template:
     metadata:
       name: pod1
       labels:
         name: httpdeploy
     spec:
      containers:
        - name: cont1
          image: httpd
          ports:
           - containerPort: 80
