kind: ReplicaSet
apiVersion: apps/v1
metadata:
     name: myrc
spec:
  replicas: 2
  selector:
    matchExpressions:                             # these must match the labels
      - {key: myname, operator: In, values: [Rohit, Rohitp, rohit]}
      - {key: env, operator: NotIn, values: [production]}
  template:
    metadata:
      name: testpod7
      labels:
        myname: Rohit
    spec:
     containers:
       - name: c00
         image: ubuntu
         command: ["/bin/bash", "-c", "while true; do echo Technical-Guftgu; sleep 5 ; done"]
